export const allFood = [
  {
    id: 1,
    name: "دلمه برگ کلم",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
      { star: "۵" },
    ],
    price: "220000",
    offPrice: "209000",
    discount: "۸",
    image: "https://s8.uupload.ir/files/1_ojc8.jpg",
  },
  {
    id: 2,
    name: "بادمجان شکم‌پر",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
      { star: "۵" },
    ],
    price: "150000",
    offPrice: "136000",
    discount: "۸",
    image: "https://s8.uupload.ir/files/2_rrsc.png",
  },
  {
    id: 3,
    name: "کالزونه اسفناج",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
      { star: "۵" },
    ],
    price: "190000",
    offPrice: "177000",
    discount: "۱۷",
    image: "https://s8.uupload.ir/files/3_jz7k.png",
  },
  {
    id: 4,
    name: "پیتزا قارچ",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
      { star: "۵" },
    ],
    price: "215000",
    offPrice: "175000",
    discount: "۲۵",
    image: "https://s8.uupload.ir/files/4_eujl.jpg",
  },
  {
    id: 5,
    name: "پنینی اسفناج",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
      { star: "۵" },
    ],
    price: "210000",
    offPrice: "190000",
    discount: "۱۵",
    image: "https://s8.uupload.ir/files/5_sklb.png",
  },
  {
    id: 6,
    name: "پیتزا پپرونی",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
      { star: "۵" },
    ],
    price: "100000",
    offPrice: "100000",
    discount: 0,
    image: "https://s8.uupload.ir/files/6_j5bs.png",
  },
  {
    id: 7,
    name: "سوشی",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
      { star: "۵" },
    ],
    price: "85000",
    offPrice: "85000",
    discount: 0,
    image: "https://s8.uupload.ir/files/8_ae9i.png",
  },
];
