export const allFood = [
  {
    id: 1,
    name: "دلمه برگ کلم",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: "۲۲۰٬۰۰۰",
    offPrice: "۲۰۹٬۰۰۰",
    discount: "۸",
    image: "https://uupload.ir/view/1_ojc8.jpg",
  },
  {
    id: 2,
    name: "بادمجان شکم‌پر",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: "۱۵۰٬۰۰۰",
    offPrice: "۱۳۶٬۰۰۰",
    discount: "۸",
    image: "https://uupload.ir/view/2_rrsc.png",
  },
  {
    id: 3,
    name: "کالزونه اسفناج",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: "۱۹۰٬۰۰۰",
    offPrice: "۱۷۷٬۰۰۰",
    discount: "۱۷",
    image: "https://uupload.ir/view/3_jz7k.png",
  },
  {
    id: 4,
    name: "پیتزا قارچ",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: "۲۱۵٬۰۰۰",
    offPrice: "۱۷۵٬۰۰۰",
    discount: "۲۵",
    image: "https://uupload.ir/view/4_eujl.jpg",
  },
  {
    id: 5,
    name: "پنینی اسفناج",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: "۲۱۰٬۰۰۰",
    offPrice: "۱۹۰٬۰۰۰",
    discount: "۱۵",
    image: "https://uupload.ir/view/5_sklb.png",
  },
  {
    id: 6,
    name: "پیتزا پپرونی",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: "۱۰۰٬۰۰۰",
    offPrice: 0,
    discount: 0,
    image: "https://uupload.ir/view/6_j5bs.png",
  },
  {
    id: 7,
    name: "سوشی",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: "۸۵٬۰۰۰",
    offPrice: 0,
    discount: 0,
    image: "https://uupload.ir/view/8_ae9i.png",
  },
];
